In [3]:
pip install numpy pandas

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
my_list=[1,2,3]
type(my_list)

list

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_list

[1, 2, 3]

In [8]:
myarr=np.array(my_list)
type(myarr)

numpy.ndarray

In [9]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(5,2)

array([[0.0089324 , 0.35389481],
       [0.48024674, 0.51544472],
       [0.04877524, 0.13839184],
       [0.348417  , 0.64536562],
       [0.06176684, 0.67507287]])

In [46]:
np.random.randn(2,3)

array([[-0.62947496,  0.59772047,  2.55948803],
       [ 0.39423302,  0.12221917, -0.51543566]])

In [19]:
np.random.randint(0,101,5)

array([78, 35, 57,  8, 40], dtype=int32)

In [20]:
np.random.randint(0,101,(2,3))

array([[14, 25, 11],
       [27, 72, 93]], dtype=int32)

In [48]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [22]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr.max()

np.int64(24)

In [25]:
arr.min()

np.int64(0)

In [26]:
my_arr=np.random.randint(0,102,10)
my_arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52], dtype=int32)

In [27]:
my_arr.max()

np.int32(99)

In [28]:
my_arr.argmax()

np.int64(5)

In [29]:
my_arr.dtype

dtype('int32')

In [30]:
my_arr.shape

(10,)

In [50]:
arr=np.arange(0,10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
arr[8]

np.int64(8)

In [33]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [37]:
l=[1,2,3,4]
l[0:3]=0
l

TypeError: must assign iterable to extended slice

In [60]:
arr=np.arange(0,11)

In [64]:
slice_of_arr=arr[0:5]
slice_of_arr

array([9, 9, 9, 9, 9])

In [65]:
slice_of_arr[:]=9

In [68]:
arr

array([ 9,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10])

In [69]:
arr_copy=arr.copy()
arr_copy[:]=5
arr,arr_copy
# print(arr_copy)


(array([ 9,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10]),
 array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))

In [71]:
my_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
my_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
my_2d.shape

(3, 3)

In [74]:
my_2d[2][1]

np.int64(8)

In [75]:
my_2d[0,2]

np.int64(3)

In [76]:
my_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
my_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [90]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
boo_arr=arr>4

In [92]:
boo_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [93]:
arr[boo_arr]

array([ 5,  6,  7,  8,  9, 10])

In [95]:
arr[arr<4]

array([1, 2, 3])

In [97]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
arr+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [99]:
arr-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [100]:
arr *2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [101]:
arr /arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [102]:
np.sqrt(16)

np.float64(4.0)

In [103]:
np.sin(1)

np.float64(0.8414709848078965)

In [104]:
arr.sum()

np.int64(45)

In [105]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
arr.var()

np.float64(6.666666666666667)

In [117]:
a1=np.arange(0,25)

In [118]:
a1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [119]:
a1.sum()

np.int64(300)

In [124]:
arr.sum(axis=0)

np.int64(45)