In [3]:
pip install numpy pandas

  Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.6 MB 2.6 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/12.6 MB 2.1 MB/s eta 0:00:06
   ----- ---------------------------------- 1.6/12.6 MB 2.0 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.6 MB 1.9 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.6 MB 1.9 MB/s eta 0:00:06
   -------- ------------------------------- 2.6/12.6 MB 1.9 MB/s eta 0:00:06
   ---------- ----------------------------- 3.1/12.6 MB 2.0 MB/s eta 0:00:05
   ---------- ----------------------------- 3.4/12.6 MB 2.0 MB/s eta 0:00:05
   ------------ --------------------------- 3.9/12.6 MB 2.0 MB/s eta 0:00:05
   -------------- -------------

In [4]:
import numpy as np

In [2]:
my_list=[1,2,3]
type(my_list)

list

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_list

[1, 2, 3]

In [7]:
myarr=np.array(my_list)
type(myarr)

numpy.ndarray

In [8]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [14]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(5,2)

array([[0.54370493, 0.34457047],
       [0.39561299, 0.59826048],
       [0.00425981, 0.44796466],
       [0.84041839, 0.48384215],
       [0.87300657, 0.06964362]])

In [22]:
np.random.randn(2,3)

array([[ 0.70527065,  0.09754927, -0.5407448 ],
       [-0.84200458, -0.27570746, -0.3756584 ]])

In [27]:
np.random.randint(0,101,5)

array([66, 17, 30, 80, 92], dtype=int32)

In [28]:
np.random.randint(0,101,(2,3))

array([[99, 75, 80],
       [98, 33, 34]], dtype=int32)

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [36]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.max()

np.int64(24)

In [39]:
arr.min()

np.int64(0)

In [43]:
my_arr=np.random.randint(0,102,10)
my_arr

array([99, 23,  2, 21, 52,  1, 87, 29, 37,  1], dtype=int32)

In [44]:
my_arr.max()

np.int32(99)

In [45]:
my_arr.argmax()

np.int64(0)

In [48]:
my_arr.dtype

dtype('int32')

In [50]:
my_arr.shape

(10,)

In [51]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr[8]

np.int64(8)

In [54]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [59]:
l=[1,2,3,4]
l[0:3]=0
l

TypeError: must assign iterable to extended slice

In [60]:
arr=np.arange(0,11)

In [64]:
slice_of_arr=arr[0:5]
slice_of_arr

array([9, 9, 9, 9, 9])

In [65]:
slice_of_arr[:]=9

In [68]:
arr

array([ 9,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10])

In [69]:
arr_copy=arr.copy()
arr_copy[:]=5
arr,arr_copy
# print(arr_copy)


(array([ 9,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10]),
 array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))

In [71]:
my_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
my_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
my_2d.shape

(3, 3)

In [74]:
my_2d[2][1]

np.int64(8)

In [75]:
my_2d[0,2]

np.int64(3)

In [76]:
my_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
my_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [90]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
boo_arr=arr>4

In [92]:
boo_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [93]:
arr[boo_arr]

array([ 5,  6,  7,  8,  9, 10])

In [95]:
arr[arr<4]

array([1, 2, 3])

In [97]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
arr+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [99]:
arr-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [100]:
arr *2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [101]:
arr /arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [102]:
np.sqrt(16)

np.float64(4.0)

In [103]:
np.sin(1)

np.float64(0.8414709848078965)

In [104]:
arr.sum()

np.int64(45)

In [105]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
arr.var()

np.float64(6.666666666666667)

In [117]:
a1=np.arange(0,25)

In [118]:
a1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [119]:
a1.sum()

np.int64(300)

In [124]:
arr.sum(axis=0)

np.int64(45)