In [35]:
# pip install pandas

Note: you may need to restart the kernel to use updated packages.


##  Pandas Series

In [36]:
import pandas as pd
import numpy as np

In [37]:
data=pd.Series([1,2,3])
data

0    1
1    2
2    3
dtype: int64

In [38]:
myindex=['USA','CANO','Mex']
data=[112,321,321]
myser=pd.Series(data=data,index=myindex)
myser

USA     112
CANO    321
Mex     321
dtype: int64

In [39]:
myser['USA']

np.int64(112)

In [40]:
age={'sam':2,'frank':90}
a=pd.Series(age)

In [41]:
a['sam']=0

In [42]:
a

sam       0
frank    90
dtype: int64

In [43]:
q1={'japan':80,'china':34,'india':32,'USA':80}
q2={'japan':90,'china':36,'india':33}

In [44]:
sales=pd.Series(q1)
sales

japan    80
china    34
india    32
USA      80
dtype: int64

In [45]:
sales1=pd.Series(q2)
sales1

japan    90
china    36
india    33
dtype: int64

In [46]:
sales.get('japan')

np.int64(80)

In [47]:
sales.keys()

Index(['japan', 'china', 'india', 'USA'], dtype='object')

In [48]:
sales.values

array([80, 34, 32, 80])

In [49]:
[1,2]*2

[1, 2, 1, 2]

In [50]:
np.array([1,2])*2

array([2, 4])

In [51]:
sales*2

japan    160
china     68
india     64
USA      160
dtype: int64

In [52]:
sales+sales1

USA        NaN
china     70.0
india     65.0
japan    170.0
dtype: float64

In [55]:
sales.add(sales1,fill_value=0)

USA       80.0
china     70.0
india     65.0
japan    170.0
dtype: float64

In [56]:
sales.dtype

dtype('int64')

## DataFrame

In [60]:
np.random.seed(101)
mydata=np.random.randint(0,101,(4,3))
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]], dtype=int32)

In [64]:
myindex=['CA','NY','Ew','Wq']
mycolumn=['Jan','Feb','Mar']

In [65]:
df=pd.DataFrame(mydata,columns=mycolumn,index=myindex)
df

Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
Ew   75    9   77
Wq   40    4   63

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to Wq
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 252.0+ bytes


In [67]:
pwd

'c:\\Work\\Python DataScience'

In [68]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 2028-DBF2

 Directory of c:\Work\Python DataScience

14-10-2024  11:54    <DIR>          .
13-10-2024  19:22    <DIR>          ..
13-10-2024  20:50                 5 .gitignore
13-10-2024  19:25    <DIR>          .venv
14-10-2024  12:15            24,119 Numpy.ipynb
16-10-2024  08:32            11,793 Pandas.ipynb
               3 File(s)         35,917 bytes
               3 Dir(s)  904,351,952,896 bytes free


In [73]:
df=pd.read_csv('.\\Data\\tips.csv')
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

In [78]:
df.shape

(244, 11)

In [74]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [77]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [76]:
df.dtypes

total_bill          float64
tip                 float64
sex                  object
smoker               object
day                  object
time                 object
size                  int64
price_per_person    float64
Payer Name           object
CC Number             int64
Payment ID           object
dtype: object

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object 
 3   smoker            244 non-null    object 
 4   day               244 non-null    object 
 5   time              244 non-null    object 
 6   size              244 non-null    int64  
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object 
 9   CC Number         244 non-null    int64  
 10  Payment ID        244 non-null    object 
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB


In [83]:
df.describe()

total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

- Information Based on Columns

In [84]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

In [85]:
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64